### ISSUE TITLE
Doesn't trigger change events in fields

### ISSUE THREAD

**Issue by OldStarchy** [TildBJ/yalig#4]
Some forms rely on a change event occurring in a field before its marked as "changed" (eg. forms generated by React).
Text added by this extension doesn't trigger a change event, so the field content is not submitted with the form.
My exact use-case is entering content in SilverStripe 4.

My current workaround is to hit "space, backspace" to trigger a change in the field after adding text with this extension.

**Comment by Schnaaf** [comment]
+1
